version: '1.0'

services:
  api:
    image: waffeling/fastapi:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres

  
  postgres:
    image: postgres 
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  minio:
    image: quay.io/minio/minio
    ports:
    - 9000:9000
    - 9001:9001
    environment:
    - MINIO_ROOT_USER=adminuser
    - MINIO_ROOT_PASSWORD=pass123456
    volumes:
    - ./image-data:/data
    command: server /data --console-address ":9001"

